### ISSUE TITLE
Enable users to connect their email accounts to JARVIS

### ISSUE THREAD

**Issue by Luna-Jia** [COSC481W-2024Winter/JARVIS#13]
**User story**:

As a CS student with a busy schedule and constant influx of emails, I want to securely connect my Google email account to the JARVIS app so that I can manage my emails more efficiently through the app's interface.

* **persona**: People who receive high volume of emails daily and seek solution to help them filter and summarize emials to foucus on high-priority communication.

* **feature**: Allows users to connect their Google email account to JARVIS, enabling email management within the app.

* **business value**: By connecting email accounts to JARVIS, users can work more efficiently, leveraging the app’s email sorting and summarizing features.

**Task List**

- [x] Design a user-friendly authentication flow for Google account integration.
- [x] Implement Firebase Auth to manage secure user authentication and session management.
- [x]  Set up the Gmail API to access and manage the user's emails after authentication.

**Acceptance Criteria**
1. The integration allows for secure OAuth authentication with Google.
2. The feature should support all modern mobile devices.

**Acceptance Tests**
1. Users should be able to link their Google email accounts to JARVIS without errors.
2. Once linked, JARVIS should be able to access the email list from the connected Google account.
3. Users should be able to unlink their Google account from JARVIS if desired.

https://github.com/COSC481W-2024Winter/JARVIS/assets/73403516/3a934bdc-e9d4-4879-ac9b-e7ced9bdefcb

**Comment by Luna-Jia** [comment]
checkout in your local repository: 
git fetch origin
git checkout luna/13-connect-email-accounts

**Comment by Luna-Jia** [comment]
**Add login feature using Firebase Auth**

Implemented user authentication using Firebase Auth, including support for email and Google sign-in. This allows users to create new accounts and log in to the app.

- Use firebase_ui_auth for UI components
- Configure Firebase auth 
- Handle sign-in and sign-out flows
- Enable Gmail API

issue #13
