### ISSUE TITLE
Collect User Email

### ISSUE THREAD

**Issue by dayshsweet** [COSC481W-2024Winter/JARVIS#16]
**User Story**
As a user who has just started navigating our application and is now able to login to our application and connect my Gmail account, I would like to have the ability to see all of my emails and their content. 

- **Persona:** A new user who has just used our application and can now login

- **Feature:** Use API to collect user's emails in one location

- **Business Value:** Users will have access to their emails within our application and the J.A.R.V.I.S. application will be able to add more functionality using the information with the email's content

**Tasks**

- [ ] fetch emails using Google API
- [ ] handle paging and filtering
- [ ] display emails in flutter application
- [ ] testing things such as network errors, API limits, and making sure emails are being retrieved/parsed/displayed

**Acceptance Criteria**

1. The application should be able to fetch emails from the user's Gmail mailbox; pagination should be used to handle large volumes of emails
2. The application should retrieve essential email details such as sender, subject, body, etc.
3. When emails are fetched, they should be in a structured format for easy processing and display
4. The application should adhere to Google's security guidelines for accessing Gmail data and adhere to privacy regulations and guidelines regarding the handling of user data
