### ISSUE TITLE
PBI 6: Redesign the UI code for all pages to unify style and layout

### ISSUE THREAD

**Issue by JacobYankee** [COSC481W-2024Winter/JARVIS#38]
**User Story**
As a modern consumer with vision problems, a clean and easily readable UI is a must for any application I use. Being able to easily tell what everything in an app does makes the experience all the better and prevents any confusion or frustration while improving productivity while using the app.
- **Persona:** Steve, a visually impaired 24 year old. Appreciates modern UI design as its simplicity and readability makes it more accessible to people like him.
- **Feature:** A streamlined UI and theme for our application.
- **Business Value:** Having a streamlined UI for every page in our application will not only make the user experience smoother but will also give our app a more professional appearance. An ease of readability through consistent theming will streamline the process of using our application and make it accessible to a larger userbase.

**Tasks:**

- [x] Create design document for app UI with Figma
- [x] Import UI design from Figma to application code

**Acceptance Criteria:**

- [x] UI has been imported to application code
