### ISSUE TITLE
PBI 4: Further UI Refinement

### ISSUE THREAD

**Issue by JacobYankee** [COSC481W-2024Winter/JARVIS#60]
**User Story**
As a modern consumer with vision problems, a clean and easily readable UI is a must for any application I use. Being able to easily tell what everything in an app does makes the experience all the better and prevents any confusion or frustration while improving productivity while using the app.

- **Persona:** Steve, a visually impaired 24 year old. Appreciates modern UI design as its simplicity and readability makes it more accessible to people like him.
- **Feature:** A further enhanced UI
- **Business Value:** A further enhanced UI will make the application appear more professional and make it more approachable for users.

**Tasks:**

- [x] Alter any new additions to application to fit UI theming
- [x] Double check every page to make sure they all follow the design criteria
- [x] Implement a dark mode

**Acceptance Criteria:**

- [x] UI has been implemented in application code
